import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./(root)/_components/NavBar";
import Footer from "./(root)/_components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Justin's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          poppins.className +
          " p-8 sm:px-16 sm:py-12 lg:px-32 lg:py-16 2xl:px-[16rem] 2xl:py-20"
        }
      >
        <NavBar />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
